name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make sure Xcode is installed
        run: ls /Applications | grep Xcode
      - name: Select Xcode 12
        run: sudo xcode-select --switch /Applications/Xcode_12.2.app
      - name: Build for macOS using swift
        run: swift build -v
      - name: Run tests
        run: swift test -v